// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnSaveScreen = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pnSaveScreen, lv_pct(105));
    lv_obj_set_height(ui_pnSaveScreen, lv_pct(105));
    lv_obj_set_align(ui_pnSaveScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnSaveScreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnSaveScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnSaveScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnSaveScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgLogo = lv_img_create(ui_pnSaveScreen);
    lv_img_set_src(ui_imgLogo, &ui_img_1651235431);
    lv_obj_set_width(ui_imgLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbTimeOnSaveScreen = lv_label_create(ui_pnSaveScreen);
    lv_obj_set_width(ui_lbTimeOnSaveScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTimeOnSaveScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbTimeOnSaveScreen, 0);
    lv_obj_set_y(ui_lbTimeOnSaveScreen, 68);
    lv_obj_set_align(ui_lbTimeOnSaveScreen, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbTimeOnSaveScreen, "Wifi");
    lv_obj_set_style_text_font(ui_lbTimeOnSaveScreen, &ui_font_Rubik_Mono, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSaveScreenInfo = lv_label_create(ui_pnSaveScreen);
    lv_obj_set_width(ui_lbSaveScreenInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSaveScreenInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSaveScreenInfo, 0);
    lv_obj_set_y(ui_lbSaveScreenInfo, 139);
    lv_obj_set_align(ui_lbSaveScreenInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lbSaveScreenInfo, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_SpinSavescreen = lv_spinner_create(ui_pnSaveScreen, 1000, 90);
    lv_obj_set_width(ui_SpinSavescreen, 100);
    lv_obj_set_height(ui_SpinSavescreen, 100);
    lv_obj_set_x(ui_SpinSavescreen, 0);
    lv_obj_set_y(ui_SpinSavescreen, 10);
    lv_obj_set_align(ui_SpinSavescreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinSavescreen, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_SpinSavescreen, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SpinSavescreen, lv_color_hex(0x05D742), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinSavescreen, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lbSaveScreenExtra = lv_label_create(ui_pnSaveScreen);
    lv_obj_set_width(ui_lbSaveScreenExtra, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSaveScreenExtra, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbSaveScreenExtra, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbSaveScreenExtra, "Searching Wifi");
    lv_obj_add_flag(ui_lbSaveScreenExtra, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbSaveScreenExtra, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btWiFiPreset1 = lv_btn_create(ui_pnSaveScreen);
    lv_obj_set_width(ui_btWiFiPreset1, 100);
    lv_obj_set_height(ui_btWiFiPreset1, 50);
    lv_obj_set_x(ui_btWiFiPreset1, -55);
    lv_obj_set_y(ui_btWiFiPreset1, 67);
    lv_obj_set_align(ui_btWiFiPreset1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btWiFiPreset1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btWiFiPreset1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbWiFiPreset1 = lv_label_create(ui_btWiFiPreset1);
    lv_obj_set_width(ui_lbWiFiPreset1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbWiFiPreset1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbWiFiPreset1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbWiFiPreset1, "PRESET");
    lv_obj_set_style_text_font(ui_lbWiFiPreset1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btWiFiPreset2 = lv_btn_create(ui_pnSaveScreen);
    lv_obj_set_width(ui_btWiFiPreset2, 100);
    lv_obj_set_height(ui_btWiFiPreset2, 50);
    lv_obj_set_x(ui_btWiFiPreset2, -55);
    lv_obj_set_y(ui_btWiFiPreset2, 124);
    lv_obj_set_align(ui_btWiFiPreset2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btWiFiPreset2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btWiFiPreset2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbWiFiPreset2 = lv_label_create(ui_btWiFiPreset2);
    lv_obj_set_width(ui_lbWiFiPreset2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbWiFiPreset2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbWiFiPreset2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbWiFiPreset2, "PRESET");
    lv_obj_set_style_text_font(ui_lbWiFiPreset2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rolWifi = lv_roller_create(ui_pnSaveScreen);
    lv_roller_set_options(ui_rolWifi, "0000000000000\nWifi2\n", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_rolWifi, 220);
    lv_obj_set_height(ui_rolWifi, 145);
    lv_obj_set_x(ui_rolWifi, 0);
    lv_obj_set_y(ui_rolWifi, -41);
    lv_obj_set_align(ui_rolWifi, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_rolWifi, &ui_font_ibmmono, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rolWifi, lv_color_hex(0x7B7676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rolWifi, 127, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btWiFiUp = lv_btn_create(ui_pnSaveScreen);
    lv_obj_set_width(ui_btWiFiUp, 50);
    lv_obj_set_height(ui_btWiFiUp, 50);
    lv_obj_set_x(ui_btWiFiUp, 55);
    lv_obj_set_y(ui_btWiFiUp, 69);
    lv_obj_set_align(ui_btWiFiUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btWiFiUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btWiFiUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbBtWifiUp = lv_label_create(ui_btWiFiUp);
    lv_obj_set_width(ui_lbBtWifiUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtWifiUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtWifiUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtWifiUp, "Up");
    lv_obj_set_style_text_font(ui_lbBtWifiUp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btWiFiDown = lv_btn_create(ui_pnSaveScreen);
    lv_obj_set_width(ui_btWiFiDown, 50);
    lv_obj_set_height(ui_btWiFiDown, 50);
    lv_obj_set_x(ui_btWiFiDown, 55);
    lv_obj_set_y(ui_btWiFiDown, 125);
    lv_obj_set_align(ui_btWiFiDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btWiFiDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btWiFiDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbBtWifiDown = lv_label_create(ui_btWiFiDown);
    lv_obj_set_width(ui_lbBtWifiDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtWifiDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtWifiDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtWifiDown, "Down");
    lv_obj_set_style_text_font(ui_lbBtWifiDown, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btWiFiScanHome = lv_btn_create(ui_pnSaveScreen);
    lv_obj_set_width(ui_btWiFiScanHome, 64);
    lv_obj_set_height(ui_btWiFiScanHome, 64);
    lv_obj_set_x(ui_btWiFiScanHome, -55);
    lv_obj_set_y(ui_btWiFiScanHome, 102);
    lv_obj_set_align(ui_btWiFiScanHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btWiFiScanHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btWiFiScanHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_btWiFiScanHome);
    lv_img_set_src(ui_Image3, &ui_img_home_60_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnTuringInfo = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pnTuringInfo, lv_pct(105));
    lv_obj_set_height(ui_pnTuringInfo, lv_pct(105));
    lv_obj_set_align(ui_pnTuringInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnTuringInfo, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnTuringInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnTuringInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnTuringInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbConstLastWater = lv_label_create(ui_pnTuringInfo);
    lv_obj_set_width(ui_lbConstLastWater, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbConstLastWater, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbConstLastWater, -1);
    lv_obj_set_y(ui_lbConstLastWater, 51);
    lv_obj_set_align(ui_lbConstLastWater, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbConstLastWater, "Last watering date:");
    lv_obj_set_style_text_font(ui_lbConstLastWater, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbLastWaterInfo = lv_label_create(ui_pnTuringInfo);
    lv_obj_set_width(ui_lbLastWaterInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbLastWaterInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbLastWaterInfo, 0);
    lv_obj_set_y(ui_lbLastWaterInfo, 75);
    lv_obj_set_align(ui_lbLastWaterInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbLastWaterInfo, "Thu, 26/04/2024");
    lv_obj_set_style_text_font(ui_lbLastWaterInfo, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imPlantHum1 = lv_img_create(ui_pnTuringInfo);
    lv_img_set_src(ui_imPlantHum1, &ui_img_humidity_48_png);
    lv_obj_set_width(ui_imPlantHum1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imPlantHum1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imPlantHum1, 0);
    lv_obj_set_y(ui_imPlantHum1, 20);
    lv_obj_add_flag(ui_imPlantHum1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imPlantHum1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbConstPlantHum1 = lv_label_create(ui_imPlantHum1);
    lv_obj_set_width(ui_lbConstPlantHum1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbConstPlantHum1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbConstPlantHum1, -7);
    lv_obj_set_y(ui_lbConstPlantHum1, 0);
    lv_obj_set_align(ui_lbConstPlantHum1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbConstPlantHum1, "1");
    lv_obj_set_style_text_color(ui_lbConstPlantHum1, lv_color_hex(0x1200FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbConstPlantHum1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbConstPlantHum1, &ui_font_Rubik_Mono, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imPlantHum2 = lv_img_create(ui_pnTuringInfo);
    lv_img_set_src(ui_imPlantHum2, &ui_img_humidity_48_png);
    lv_obj_set_width(ui_imPlantHum2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imPlantHum2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imPlantHum2, -1);
    lv_obj_set_y(ui_imPlantHum2, 80);
    lv_obj_add_flag(ui_imPlantHum2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imPlantHum2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbConsPlantHum2 = lv_label_create(ui_imPlantHum2);
    lv_obj_set_width(ui_lbConsPlantHum2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbConsPlantHum2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbConsPlantHum2, -7);
    lv_obj_set_y(ui_lbConsPlantHum2, 0);
    lv_obj_set_align(ui_lbConsPlantHum2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbConsPlantHum2, "2");
    lv_obj_set_style_text_color(ui_lbConsPlantHum2, lv_color_hex(0x1200FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbConsPlantHum2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbConsPlantHum2, &ui_font_Rubik_Mono, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPlantOneVal = lv_label_create(ui_pnTuringInfo);
    lv_obj_set_width(ui_lbPlantOneVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPlantOneVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPlantOneVal, -24);
    lv_obj_set_y(ui_lbPlantOneVal, 29);
    lv_obj_set_align(ui_lbPlantOneVal, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbPlantOneVal, "100%");
    lv_label_set_recolor(ui_lbPlantOneVal, "true");
    lv_obj_set_style_text_font(ui_lbPlantOneVal, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbPlantTwoVal = lv_label_create(ui_pnTuringInfo);
    lv_obj_set_width(ui_lbPlantTwoVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbPlantTwoVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbPlantTwoVal, -24);
    lv_obj_set_y(ui_lbPlantTwoVal, 87);
    lv_obj_set_align(ui_lbPlantTwoVal, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbPlantTwoVal, "100%");
    lv_label_set_recolor(ui_lbPlantTwoVal, "true");
    lv_obj_set_style_text_font(ui_lbPlantTwoVal, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imTemp = lv_img_create(ui_pnTuringInfo);
    lv_img_set_src(ui_imTemp, &ui_img_temperature_leaf_64_png);
    lv_obj_set_width(ui_imTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imTemp, -2);
    lv_obj_set_y(ui_imTemp, 132);
    lv_obj_add_flag(ui_imTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbTempVal = lv_label_create(ui_pnTuringInfo);
    lv_obj_set_width(ui_lbTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbTempVal, -24);
    lv_obj_set_y(ui_lbTempVal, 137);
    lv_obj_set_align(ui_lbTempVal, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbTempVal, "#ff0000 26.5#°C");
    lv_label_set_recolor(ui_lbTempVal, "true");
    lv_obj_set_style_text_font(ui_lbTempVal, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barTankVal = lv_bar_create(ui_pnTuringInfo);
    lv_bar_set_value(ui_barTankVal, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barTankVal, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barTankVal, 59);
    lv_obj_set_height(ui_barTankVal, 141);
    lv_obj_set_x(ui_barTankVal, 73);
    lv_obj_set_y(ui_barTankVal, -44);
    lv_obj_set_align(ui_barTankVal, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barTankVal, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barTankVal, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lbTankVal = lv_label_create(ui_pnTuringInfo);
    lv_obj_set_width(ui_lbTankVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTankVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbTankVal, 77);
    lv_obj_set_y(ui_lbTankVal, 92);
    lv_obj_set_align(ui_lbTankVal, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbTankVal, "#00f0ff 100#%");
    lv_label_set_recolor(ui_lbTankVal, "true");
    lv_obj_set_style_text_font(ui_lbTankVal, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbTempVal1 = lv_label_create(ui_pnTuringInfo);
    lv_obj_set_width(ui_lbTempVal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTempVal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbTempVal1, 76);
    lv_obj_set_y(ui_lbTempVal1, 1);
    lv_obj_set_align(ui_lbTempVal1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbTempVal1, "Tank");
    lv_obj_set_style_text_font(ui_lbTempVal1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnMainMenu = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pnMainMenu, lv_pct(105));
    lv_obj_set_height(ui_pnMainMenu, lv_pct(105));
    lv_obj_set_align(ui_pnMainMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnMainMenu, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnMainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnMainMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnMainMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMenuInfo = lv_label_create(ui_pnMainMenu);
    lv_obj_set_width(ui_lbMenuInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMenuInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMenuInfo, 2);
    lv_obj_set_y(ui_lbMenuInfo, 0);
    lv_obj_set_align(ui_lbMenuInfo, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbMenuInfo, "Thu, 26/04/2024");
    lv_label_set_recolor(ui_lbMenuInfo, "true");

    ui_lbMainMenuInfoUpper = lv_label_create(ui_pnMainMenu);
    lv_obj_set_width(ui_lbMainMenuInfoUpper, 230);
    lv_obj_set_height(ui_lbMainMenuInfoUpper, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainMenuInfoUpper, 0);
    lv_obj_set_y(ui_lbMainMenuInfoUpper, 20);
    lv_obj_set_align(ui_lbMainMenuInfoUpper, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_lbMainMenuInfoUpper, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_lbMainMenuInfoUpper, "Ready!");
    lv_label_set_recolor(ui_lbMainMenuInfoUpper, "true");
    lv_obj_set_style_text_align(ui_lbMainMenuInfoUpper, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbMainMenuInfoUpper, &ui_font_ibmmono, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btHomeWifiConfig = lv_btn_create(ui_pnMainMenu);
    lv_obj_set_width(ui_btHomeWifiConfig, 64);
    lv_obj_set_height(ui_btHomeWifiConfig, 64);
    lv_obj_set_x(ui_btHomeWifiConfig, -76);
    lv_obj_set_y(ui_btHomeWifiConfig, -48);
    lv_obj_set_align(ui_btHomeWifiConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btHomeWifiConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btHomeWifiConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_btHomeWifiConfig);
    lv_img_set_src(ui_Image1, &ui_img_wifi_green_60_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image1, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btHomeTuring = lv_btn_create(ui_pnMainMenu);
    lv_obj_set_width(ui_btHomeTuring, 64);
    lv_obj_set_height(ui_btHomeTuring, 64);
    lv_obj_set_x(ui_btHomeTuring, 0);
    lv_obj_set_y(ui_btHomeTuring, -48);
    lv_obj_set_align(ui_btHomeTuring, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_btHomeTuring, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_btHomeTuring, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btHomeTuring, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btHomeTuring, lv_color_hex(0x887D7D), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_btHomeTuring, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_imgBtHomeTuring = lv_img_create(ui_btHomeTuring);
    lv_img_set_src(ui_imgBtHomeTuring, &ui_img_temperature_48_png);
    lv_obj_set_width(ui_imgBtHomeTuring, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBtHomeTuring, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgBtHomeTuring, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBtHomeTuring, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBtHomeTuring, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_imgBtHomeTuring, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_imgBtHomeTuring, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btHomeWarning = lv_btn_create(ui_pnMainMenu);
    lv_obj_set_width(ui_btHomeWarning, 64);
    lv_obj_set_height(ui_btHomeWarning, 64);
    lv_obj_set_x(ui_btHomeWarning, 76);
    lv_obj_set_y(ui_btHomeWarning, -48);
    lv_obj_set_align(ui_btHomeWarning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btHomeWarning, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btHomeWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageBtHomeWarning = lv_img_create(ui_btHomeWarning);
    lv_img_set_src(ui_imageBtHomeWarning, &ui_img_warning_red_48_png);
    lv_obj_set_width(ui_imageBtHomeWarning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageBtHomeWarning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imageBtHomeWarning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageBtHomeWarning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageBtHomeWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btHomeInfo = lv_btn_create(ui_pnMainMenu);
    lv_obj_set_width(ui_btHomeInfo, 64);
    lv_obj_set_height(ui_btHomeInfo, 64);
    lv_obj_set_x(ui_btHomeInfo, -76);
    lv_obj_set_y(ui_btHomeInfo, 31);
    lv_obj_set_align(ui_btHomeInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btHomeInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btHomeInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_btHomeInfo);
    lv_img_set_src(ui_Image6, &ui_img_info_60_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btHomeSettings = lv_btn_create(ui_pnMainMenu);
    lv_obj_set_width(ui_btHomeSettings, 64);
    lv_obj_set_height(ui_btHomeSettings, 64);
    lv_obj_set_x(ui_btHomeSettings, 0);
    lv_obj_set_y(ui_btHomeSettings, 31);
    lv_obj_set_align(ui_btHomeSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btHomeSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btHomeSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_btHomeSettings);
    lv_img_set_src(ui_Image7, &ui_img_gear_60_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btHomeLock = lv_btn_create(ui_pnMainMenu);
    lv_obj_set_width(ui_btHomeLock, 64);
    lv_obj_set_height(ui_btHomeLock, 64);
    lv_obj_set_x(ui_btHomeLock, 76);
    lv_obj_set_y(ui_btHomeLock, 31);
    lv_obj_set_align(ui_btHomeLock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btHomeLock, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btHomeLock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_btHomeLock);
    lv_img_set_src(ui_Image8, &ui_img_lock_60_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbMainMenuInfoLower = lv_label_create(ui_pnMainMenu);
    lv_obj_set_width(ui_lbMainMenuInfoLower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainMenuInfoLower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainMenuInfoLower, 0);
    lv_obj_set_y(ui_lbMainMenuInfoLower, 240);
    lv_obj_set_align(ui_lbMainMenuInfoLower, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbMainMenuInfoLower, "Ready!");
    lv_label_set_recolor(ui_lbMainMenuInfoLower, "true");
    lv_obj_set_style_text_font(ui_lbMainMenuInfoLower, &ui_font_ibmmono, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btHomeDisableWarning = lv_btn_create(ui_pnMainMenu);
    lv_obj_set_width(ui_btHomeDisableWarning, 216);
    lv_obj_set_height(ui_btHomeDisableWarning, 50);
    lv_obj_set_x(ui_btHomeDisableWarning, 0);
    lv_obj_set_y(ui_btHomeDisableWarning, 102);
    lv_obj_set_align(ui_btHomeDisableWarning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btHomeDisableWarning, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btHomeDisableWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbContBtWaterNow4 = lv_label_create(ui_btHomeDisableWarning);
    lv_obj_set_width(ui_lbContBtWaterNow4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbContBtWaterNow4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbContBtWaterNow4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbContBtWaterNow4, "Disable LED");
    lv_obj_set_style_text_font(ui_lbContBtWaterNow4, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btHomeWater = lv_btn_create(ui_pnMainMenu);
    lv_obj_set_width(ui_btHomeWater, 64);
    lv_obj_set_height(ui_btHomeWater, 64);
    lv_obj_set_x(ui_btHomeWater, 76);
    lv_obj_set_y(ui_btHomeWater, 110);
    lv_obj_set_align(ui_btHomeWater, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btHomeWater, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btHomeWater, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_btHomeWater);
    lv_img_set_src(ui_Image9, &ui_img_hose__60_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btHomeLight = lv_btn_create(ui_pnMainMenu);
    lv_obj_set_width(ui_btHomeLight, 64);
    lv_obj_set_height(ui_btHomeLight, 64);
    lv_obj_set_x(ui_btHomeLight, 0);
    lv_obj_set_y(ui_btHomeLight, 110);
    lv_obj_set_align(ui_btHomeLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btHomeLight, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btHomeLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_btHomeLight);
    lv_img_set_src(ui_Image10, &ui_img_light_60_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btHomeMonitor = lv_btn_create(ui_pnMainMenu);
    lv_obj_set_width(ui_btHomeMonitor, 64);
    lv_obj_set_height(ui_btHomeMonitor, 64);
    lv_obj_set_x(ui_btHomeMonitor, 76);
    lv_obj_set_y(ui_btHomeMonitor, 31);
    lv_obj_set_align(ui_btHomeMonitor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btHomeMonitor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btHomeMonitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageBtHomeMonitor = lv_img_create(ui_btHomeMonitor);
    lv_img_set_src(ui_imageBtHomeMonitor, &ui_img_monitor_48_png);
    lv_obj_set_width(ui_imageBtHomeMonitor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageBtHomeMonitor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imageBtHomeMonitor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageBtHomeMonitor, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageBtHomeMonitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnTest = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pnTest, lv_pct(105));
    lv_obj_set_height(ui_pnTest, lv_pct(105));
    lv_obj_set_x(ui_pnTest, 3);
    lv_obj_set_y(ui_pnTest, 0);
    lv_obj_set_align(ui_pnTest, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnTest, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnTest, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbTestLow = lv_label_create(ui_pnTest);
    lv_obj_set_width(ui_lbTestLow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTestLow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbTestLow, 0);
    lv_obj_set_y(ui_lbTestLow, -78);
    lv_obj_set_align(ui_lbTestLow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbTestLow, "Thu, 26/04/2024");

    ui_lbTestBig = lv_label_create(ui_pnTest);
    lv_obj_set_width(ui_lbTestBig, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbTestBig, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbTestBig, -4);
    lv_obj_set_y(ui_lbTestBig, 1);
    lv_obj_set_align(ui_lbTestBig, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbTestBig, "Plant One:");
    lv_obj_set_style_text_font(ui_lbTestBig, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btTest = lv_btn_create(ui_pnTest);
    lv_obj_set_width(ui_btTest, 202);
    lv_obj_set_height(ui_btTest, 50);
    lv_obj_set_x(ui_btTest, -2);
    lv_obj_set_y(ui_btTest, 103);
    lv_obj_set_align(ui_btTest, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbContBtWaterNow2 = lv_label_create(ui_pnTest);
    lv_obj_set_width(ui_lbContBtWaterNow2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbContBtWaterNow2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbContBtWaterNow2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbContBtWaterNow2, "Water Now");
    lv_obj_set_style_text_font(ui_lbContBtWaterNow2, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnInfo = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pnInfo, lv_pct(105));
    lv_obj_set_height(ui_pnInfo, lv_pct(105));
    lv_obj_set_x(ui_pnInfo, 0);
    lv_obj_set_y(ui_pnInfo, -1);
    lv_obj_set_align(ui_pnInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnInfo, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbInfoBody = lv_label_create(ui_pnInfo);
    lv_obj_set_width(ui_lbInfoBody, 220);
    lv_obj_set_height(ui_lbInfoBody, 210);
    lv_obj_set_x(ui_lbInfoBody, 0);
    lv_obj_set_y(ui_lbInfoBody, -10);
    lv_obj_set_align(ui_lbInfoBody, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbInfoBody, "Mac: \nWiFi:\nStorage:\n");
    lv_label_set_recolor(ui_lbInfoBody, "true");
    lv_obj_set_style_text_align(ui_lbInfoBody, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbInfoBody, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbInfoTitle = lv_label_create(ui_pnInfo);
    lv_obj_set_width(ui_lbInfoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbInfoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbInfoTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbInfoTitle, "Alan Turing");
    lv_label_set_recolor(ui_lbInfoTitle, "true");
    lv_obj_set_style_text_font(ui_lbInfoTitle, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnSettings = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pnSettings, lv_pct(105));
    lv_obj_set_height(ui_pnSettings, lv_pct(105));
    lv_obj_set_x(ui_pnSettings, 0);
    lv_obj_set_y(ui_pnSettings, -1);
    lv_obj_set_align(ui_pnSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnSettings, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSettingsTitle = lv_label_create(ui_pnSettings);
    lv_obj_set_width(ui_lbSettingsTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSettingsTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbSettingsTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbSettingsTitle, "Settings");
    lv_label_set_recolor(ui_lbSettingsTitle, "true");
    lv_obj_set_style_text_font(ui_lbSettingsTitle, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swEnableLed = lv_switch_create(ui_pnSettings);
    lv_obj_set_width(ui_swEnableLed, 65);
    lv_obj_set_height(ui_swEnableLed, 35);
    lv_obj_set_x(ui_swEnableLed, 65);
    lv_obj_set_y(ui_swEnableLed, -88);
    lv_obj_set_align(ui_swEnableLed, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_swEnableLed, lv_color_hex(0x5B5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swEnableLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_swEnableLed, lv_color_hex(0x05D742), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_swEnableLed, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_lbConstSwLed = lv_label_create(ui_pnSettings);
    lv_obj_set_width(ui_lbConstSwLed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbConstSwLed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbConstSwLed, -54);
    lv_obj_set_y(ui_lbConstSwLed, -87);
    lv_obj_set_align(ui_lbConstSwLed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbConstSwLed, "Enable LED");
    lv_obj_set_style_text_font(ui_lbConstSwLed, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbConstDeep = lv_label_create(ui_pnSettings);
    lv_obj_set_width(ui_lbConstDeep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbConstDeep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbConstDeep, -54);
    lv_obj_set_y(ui_lbConstDeep, -45);
    lv_obj_set_align(ui_lbConstDeep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbConstDeep, "Deep Sleep");
    lv_obj_set_style_text_font(ui_lbConstDeep, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swDeepSleep = lv_switch_create(ui_pnSettings);
    lv_obj_set_width(ui_swDeepSleep, 65);
    lv_obj_set_height(ui_swDeepSleep, 35);
    lv_obj_set_x(ui_swDeepSleep, 65);
    lv_obj_set_y(ui_swDeepSleep, -47);
    lv_obj_set_align(ui_swDeepSleep, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_swDeepSleep, lv_color_hex(0x5B5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swDeepSleep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_swDeepSleep, lv_color_hex(0x05D742), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_swDeepSleep, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_lbConstSS = lv_label_create(ui_pnSettings);
    lv_obj_set_width(ui_lbConstSS, 120);
    lv_obj_set_height(ui_lbConstSS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbConstSS, -54);
    lv_obj_set_y(ui_lbConstSS, -3);
    lv_obj_set_align(ui_lbConstSS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbConstSS, "Enable SaveScreen");
    lv_obj_set_style_text_align(ui_lbConstSS, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbConstSS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swEnableSa = lv_switch_create(ui_pnSettings);
    lv_obj_set_width(ui_swEnableSa, 65);
    lv_obj_set_height(ui_swEnableSa, 35);
    lv_obj_set_x(ui_swEnableSa, 65);
    lv_obj_set_y(ui_swEnableSa, -5);
    lv_obj_set_align(ui_swEnableSa, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_swEnableSa, lv_color_hex(0x5B5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swEnableSa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_swEnableSa, lv_color_hex(0x05D742), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_swEnableSa, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_lbConstBrightness = lv_label_create(ui_pnSettings);
    lv_obj_set_width(ui_lbConstBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbConstBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbConstBrightness, 0);
    lv_obj_set_y(ui_lbConstBrightness, 33);
    lv_obj_set_align(ui_lbConstBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbConstBrightness, "Brightness");
    lv_obj_set_style_text_font(ui_lbConstBrightness, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slBrightness = lv_slider_create(ui_pnSettings);
    lv_slider_set_range(ui_slBrightness, 32, 255);
    lv_slider_set_value(ui_slBrightness, 127, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_slBrightness, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_slBrightness, 200);
    lv_obj_set_height(ui_slBrightness, 15);
    lv_obj_set_x(ui_slBrightness, 0);
    lv_obj_set_y(ui_slBrightness, 60);
    lv_obj_set_align(ui_slBrightness, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_slBrightness, lv_color_hex(0x5B5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_slBrightness, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slBrightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_btSettingsSetHomeScreen = lv_btn_create(ui_pnSettings);
    lv_obj_set_width(ui_btSettingsSetHomeScreen, 120);
    lv_obj_set_height(ui_btSettingsSetHomeScreen, 52);
    lv_obj_set_x(ui_btSettingsSetHomeScreen, -10);
    lv_obj_set_y(ui_btSettingsSetHomeScreen, -62);
    lv_obj_set_align(ui_btSettingsSetHomeScreen, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btSettingsSetHomeScreen, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btSettingsSetHomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbConstBtSettingsReboot1 = lv_label_create(ui_btSettingsSetHomeScreen);
    lv_obj_set_width(ui_lbConstBtSettingsReboot1, 100);
    lv_obj_set_height(ui_lbConstBtSettingsReboot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbConstBtSettingsReboot1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbConstBtSettingsReboot1, "Set Home Screen");
    lv_obj_set_style_text_align(ui_lbConstBtSettingsReboot1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbConstBtSettingsReboot1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btSettingsReboot = lv_btn_create(ui_pnSettings);
    lv_obj_set_width(ui_btSettingsReboot, 120);
    lv_obj_set_height(ui_btSettingsReboot, 52);
    lv_obj_set_x(ui_btSettingsReboot, 39);
    lv_obj_set_y(ui_btSettingsReboot, 0);
    lv_obj_set_align(ui_btSettingsReboot, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btSettingsReboot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btSettingsReboot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btSettingsReboot, lv_color_hex(0xA50000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btSettingsReboot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbConstBtSettingsReboot = lv_label_create(ui_btSettingsReboot);
    lv_obj_set_width(ui_lbConstBtSettingsReboot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbConstBtSettingsReboot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbConstBtSettingsReboot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbConstBtSettingsReboot, "Reboot");
    lv_obj_set_style_text_font(ui_lbConstBtSettingsReboot, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnSetHomeScreen = lv_obj_create(ui_pnSettings);
    lv_obj_set_width(ui_pnSetHomeScreen, 219);
    lv_obj_set_height(ui_pnSetHomeScreen, 266);
    lv_obj_set_x(ui_pnSetHomeScreen, -2);
    lv_obj_set_y(ui_pnSetHomeScreen, 18);
    lv_obj_set_align(ui_pnSetHomeScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnSetHomeScreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnSetHomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_pnSetHomeScreen);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 64);
    lv_obj_set_x(ui_Button3, -53);
    lv_obj_set_y(ui_Button3, 99);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_pnSetHomeScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -5);
    lv_obj_set_y(ui_Label3, -114);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Default Screen:");

    ui_Roller1 = lv_roller_create(ui_pnSetHomeScreen);
    lv_roller_set_options(ui_Roller1, "Menu	\nTuring\n", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller1, 200);
    lv_obj_set_height(ui_Roller1, 141);
    lv_obj_set_x(ui_Roller1, -3);
    lv_obj_set_y(ui_Roller1, -22);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_Roller1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller1, &ui_font_ibmmono, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnWarnings = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pnWarnings, lv_pct(105));
    lv_obj_set_height(ui_pnWarnings, lv_pct(105));
    lv_obj_set_align(ui_pnWarnings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnWarnings, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnWarnings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnWarnings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnWarnings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbWarningTitle = lv_label_create(ui_pnWarnings);
    lv_obj_set_width(ui_lbWarningTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbWarningTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbWarningTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbWarningTitle, "Warnings");
    lv_label_set_recolor(ui_lbWarningTitle, "true");
    lv_obj_set_style_text_font(ui_lbWarningTitle, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnWarningUpper = lv_obj_create(ui_pnWarnings);
    lv_obj_set_width(ui_pnWarningUpper, 220);
    lv_obj_set_height(ui_pnWarningUpper, 84);
    lv_obj_set_x(ui_pnWarningUpper, 0);
    lv_obj_set_y(ui_pnWarningUpper, -65);
    lv_obj_set_align(ui_pnWarningUpper, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnWarningUpper, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbWarningUpperTitle = lv_label_create(ui_pnWarningUpper);
    lv_obj_set_width(ui_lbWarningUpperTitle, 210);
    lv_obj_set_height(ui_lbWarningUpperTitle, 56);
    lv_obj_set_x(ui_lbWarningUpperTitle, 0);
    lv_obj_set_y(ui_lbWarningUpperTitle, -10);
    lv_obj_set_align(ui_lbWarningUpperTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbWarningUpperTitle, "0123456789012345678901234564");
    lv_label_set_recolor(ui_lbWarningUpperTitle, "true");
    lv_obj_set_style_text_align(ui_lbWarningUpperTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbWarningUpperTitle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbWarningUpperFooter = lv_label_create(ui_pnWarningUpper);
    lv_obj_set_width(ui_lbWarningUpperFooter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbWarningUpperFooter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbWarningUpperFooter, 0);
    lv_obj_set_y(ui_lbWarningUpperFooter, 10);
    lv_obj_set_align(ui_lbWarningUpperFooter, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbWarningUpperFooter, "Raised on: 07/07/07 16:02");
    lv_label_set_recolor(ui_lbWarningUpperFooter, "true");

    ui_pnWarningLower = lv_obj_create(ui_pnWarnings);
    lv_obj_set_width(ui_pnWarningLower, 220);
    lv_obj_set_height(ui_pnWarningLower, 84);
    lv_obj_set_x(ui_pnWarningLower, 0);
    lv_obj_set_y(ui_pnWarningLower, 35);
    lv_obj_set_align(ui_pnWarningLower, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnWarningLower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbWarningLowerTitle = lv_label_create(ui_pnWarningLower);
    lv_obj_set_width(ui_lbWarningLowerTitle, 210);
    lv_obj_set_height(ui_lbWarningLowerTitle, 56);
    lv_obj_set_x(ui_lbWarningLowerTitle, 0);
    lv_obj_set_y(ui_lbWarningLowerTitle, -10);
    lv_obj_set_align(ui_lbWarningLowerTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbWarningLowerTitle, "0123456789012345678901234564");
    lv_label_set_recolor(ui_lbWarningLowerTitle, "true");
    lv_obj_set_style_text_align(ui_lbWarningLowerTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbWarningLowerTitle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbWarningLowerFooter = lv_label_create(ui_pnWarningLower);
    lv_obj_set_width(ui_lbWarningLowerFooter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbWarningLowerFooter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbWarningLowerFooter, 0);
    lv_obj_set_y(ui_lbWarningLowerFooter, 10);
    lv_obj_set_align(ui_lbWarningLowerFooter, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbWarningLowerFooter, "Raised on: 07/07/07 16:02");
    lv_label_set_recolor(ui_lbWarningLowerFooter, "true");

    ui_pnMonitor = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pnMonitor, lv_pct(105));
    lv_obj_set_height(ui_pnMonitor, lv_pct(105));
    lv_obj_set_align(ui_pnMonitor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnMonitor, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnMonitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnMonitor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnMonitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMonitorBody = lv_label_create(ui_pnMonitor);
    lv_obj_set_width(ui_lbMonitorBody, 240);
    lv_obj_set_height(ui_lbMonitorBody, 220);
    lv_obj_set_x(ui_lbMonitorBody, 0);
    lv_obj_set_y(ui_lbMonitorBody, -10);
    lv_obj_set_align(ui_lbMonitorBody, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMonitorBody, " SENSOR  |VALUE\nSENSOR 1|4095");
    lv_label_set_recolor(ui_lbMonitorBody, "true");
    lv_obj_set_style_text_align(ui_lbMonitorBody, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbMonitorBody, &ui_font_ibmmono, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMonitorTitle = lv_label_create(ui_pnMonitor);
    lv_obj_set_width(ui_lbMonitorTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMonitorTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMonitorTitle, 0);
    lv_obj_set_y(ui_lbMonitorTitle, -5);
    lv_obj_set_align(ui_lbMonitorTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbMonitorTitle, "Live Monitor");
    lv_label_set_recolor(ui_lbMonitorTitle, "true");
    lv_obj_set_style_text_font(ui_lbMonitorTitle, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnNetwork = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pnNetwork, lv_pct(105));
    lv_obj_set_height(ui_pnNetwork, lv_pct(105));
    lv_obj_set_x(ui_pnNetwork, 0);
    lv_obj_set_y(ui_pnNetwork, -1);
    lv_obj_set_align(ui_pnNetwork, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnNetwork, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnNetwork, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnNetwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbNetworkBody = lv_label_create(ui_pnNetwork);
    lv_obj_set_width(ui_lbNetworkBody, 220);
    lv_obj_set_height(ui_lbNetworkBody, 210);
    lv_obj_set_x(ui_lbNetworkBody, 0);
    lv_obj_set_y(ui_lbNetworkBody, -10);
    lv_obj_set_align(ui_lbNetworkBody, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbNetworkBody, "Mac: \nWiFi:\nStorage:\n");
    lv_label_set_recolor(ui_lbNetworkBody, "true");
    lv_obj_set_style_text_align(ui_lbNetworkBody, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbNetworkBody, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbNetworkTitle = lv_label_create(ui_pnNetwork);
    lv_obj_set_width(ui_lbNetworkTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbNetworkTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbNetworkTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbNetworkTitle, "Network");
    lv_label_set_recolor(ui_lbNetworkTitle, "true");
    lv_obj_set_style_text_font(ui_lbNetworkTitle, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btNetworkExtra1 = lv_btn_create(ui_pnNetwork);
    lv_obj_set_width(ui_btNetworkExtra1, 52);
    lv_obj_set_height(ui_btNetworkExtra1, 52);
    lv_obj_set_x(ui_btNetworkExtra1, -76);
    lv_obj_set_y(ui_btNetworkExtra1, -70);
    lv_obj_set_align(ui_btNetworkExtra1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btNetworkExtra1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btNetworkExtra1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbNetworkExtra1 = lv_label_create(ui_btNetworkExtra1);
    lv_obj_set_width(ui_lbNetworkExtra1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbNetworkExtra1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbNetworkExtra1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbNetworkExtra1, "1");
    lv_label_set_recolor(ui_lbNetworkExtra1, "true");
    lv_obj_set_style_text_font(ui_lbNetworkExtra1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btNetworkExtra2 = lv_btn_create(ui_pnNetwork);
    lv_obj_set_width(ui_btNetworkExtra2, 52);
    lv_obj_set_height(ui_btNetworkExtra2, 52);
    lv_obj_set_x(ui_btNetworkExtra2, 0);
    lv_obj_set_y(ui_btNetworkExtra2, -70);
    lv_obj_set_align(ui_btNetworkExtra2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btNetworkExtra2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btNetworkExtra2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbNetworkExtra2 = lv_label_create(ui_btNetworkExtra2);
    lv_obj_set_width(ui_lbNetworkExtra2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbNetworkExtra2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbNetworkExtra2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbNetworkExtra2, "2");
    lv_label_set_recolor(ui_lbNetworkExtra2, "true");
    lv_obj_set_style_text_font(ui_lbNetworkExtra2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btNetworkExtra3 = lv_btn_create(ui_pnNetwork);
    lv_obj_set_width(ui_btNetworkExtra3, 52);
    lv_obj_set_height(ui_btNetworkExtra3, 52);
    lv_obj_set_x(ui_btNetworkExtra3, 76);
    lv_obj_set_y(ui_btNetworkExtra3, -70);
    lv_obj_set_align(ui_btNetworkExtra3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btNetworkExtra3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btNetworkExtra3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbNetworkExtra3 = lv_label_create(ui_btNetworkExtra3);
    lv_obj_set_width(ui_lbNetworkExtra3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbNetworkExtra3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbNetworkExtra3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lbNetworkExtra3, "3");
    lv_label_set_recolor(ui_lbNetworkExtra3, "true");
    lv_obj_set_style_text_font(ui_lbNetworkExtra3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ctNavigator = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ctNavigator);
    lv_obj_set_width(ui_ctNavigator, 240);
    lv_obj_set_height(ui_ctNavigator, 60);
    lv_obj_set_x(ui_ctNavigator, 0);
    lv_obj_set_y(ui_ctNavigator, -4);
    lv_obj_set_align(ui_ctNavigator, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_ctNavigator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btNavBig = lv_btn_create(ui_ctNavigator);
    lv_obj_set_width(ui_btNavBig, 152);
    lv_obj_set_height(ui_btNavBig, 52);
    lv_obj_set_x(ui_btNavBig, 36);
    lv_obj_set_y(ui_btNavBig, 0);
    lv_obj_set_align(ui_btNavBig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btNavBig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btNavBig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbBtnNavBig = lv_label_create(ui_btNavBig);
    lv_obj_set_width(ui_lbBtnNavBig, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtnNavBig, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtnNavBig, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtnNavBig, "Water Now");
    lv_obj_set_style_text_font(ui_lbBtnNavBig, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btNavLeft = lv_btn_create(ui_ctNavigator);
    lv_obj_set_width(ui_btNavLeft, 52);
    lv_obj_set_height(ui_btNavLeft, 52);
    lv_obj_set_x(ui_btNavLeft, -76);
    lv_obj_set_y(ui_btNavLeft, 0);
    lv_obj_set_align(ui_btNavLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btNavLeft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btNavLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgBtnNavLeft = lv_img_create(ui_btNavLeft);
    lv_img_set_src(ui_imgBtnNavLeft, &ui_img_confirm_48_png);
    lv_obj_set_width(ui_imgBtnNavLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBtnNavLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgBtnNavLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBtnNavLeft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBtnNavLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_imgBtnNavLeft, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_imgBtnNavLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbBtnNavLeft = lv_label_create(ui_btNavLeft);
    lv_obj_set_width(ui_lbBtnNavLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtnNavLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtnNavLeft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtnNavLeft, "-");
    lv_obj_set_style_text_font(ui_lbBtnNavLeft, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btNavMid = lv_btn_create(ui_ctNavigator);
    lv_obj_set_width(ui_btNavMid, 52);
    lv_obj_set_height(ui_btNavMid, 52);
    lv_obj_set_align(ui_btNavMid, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btNavMid, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btNavMid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgBtnNavMid = lv_img_create(ui_btNavMid);
    lv_img_set_src(ui_imgBtnNavMid, &ui_img_magnifier_48_png);
    lv_obj_set_width(ui_imgBtnNavMid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBtnNavMid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgBtnNavMid, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBtnNavMid, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBtnNavMid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbBtnNavMid = lv_label_create(ui_btNavMid);
    lv_obj_set_width(ui_lbBtnNavMid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtnNavMid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtnNavMid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtnNavMid, "<");
    lv_obj_set_style_text_font(ui_lbBtnNavMid, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btNavRight = lv_btn_create(ui_ctNavigator);
    lv_obj_set_width(ui_btNavRight, 52);
    lv_obj_set_height(ui_btNavRight, 52);
    lv_obj_set_x(ui_btNavRight, 76);
    lv_obj_set_y(ui_btNavRight, 0);
    lv_obj_set_align(ui_btNavRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btNavRight, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btNavRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgBtnNavRight = lv_img_create(ui_btNavRight);
    lv_img_set_src(ui_imgBtnNavRight, &ui_img_home_yellow_48_png);
    lv_obj_set_width(ui_imgBtnNavRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBtnNavRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgBtnNavRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBtnNavRight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgBtnNavRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbBtnNavRight = lv_label_create(ui_btNavRight);
    lv_obj_set_width(ui_lbBtnNavRight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBtnNavRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBtnNavRight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbBtnNavRight, ">");
    lv_obj_set_style_text_font(ui_lbBtnNavRight, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnLoading = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pnLoading, lv_pct(105));
    lv_obj_set_height(ui_pnLoading, lv_pct(105));
    lv_obj_set_x(ui_pnLoading, 0);
    lv_obj_set_y(ui_pnLoading, -1);
    lv_obj_set_align(ui_pnLoading, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnLoading, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnLoading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnLoading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnLoading, 175, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spinLoadin = lv_spinner_create(ui_pnLoading, 1000, 90);
    lv_obj_set_width(ui_spinLoadin, 200);
    lv_obj_set_height(ui_spinLoadin, 200);
    lv_obj_set_align(ui_spinLoadin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_spinLoadin, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_spinLoadin, lv_color_hex(0x00FF1F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spinLoadin, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lbSpin = lv_label_create(ui_pnLoading);
    lv_obj_set_width(ui_lbSpin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbSpin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpin, "Loading");
    lv_obj_set_style_text_font(ui_lbSpin, &ui_font_Pappermint, LV_PART_MAIN | LV_STATE_DEFAULT);

}
