// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_pnSaveScreen;
lv_obj_t * ui_imgLogo;
lv_obj_t * ui_lbTimeOnSaveScreen;
lv_obj_t * ui_lbSaveScreenInfo;
lv_obj_t * ui_SpinSavescreen;
lv_obj_t * ui_lbSaveScreenExtra;
lv_obj_t * ui_btWiFiPreset1;
lv_obj_t * ui_lbWiFiPreset1;
lv_obj_t * ui_btWiFiPreset2;
lv_obj_t * ui_lbWiFiPreset2;
lv_obj_t * ui_rolWifi;
lv_obj_t * ui_btWiFiUp;
lv_obj_t * ui_lbBtWifiUp;
lv_obj_t * ui_btWiFiDown;
lv_obj_t * ui_lbBtWifiDown;
lv_obj_t * ui_btWiFiScanHome;
lv_obj_t * ui_Image3;
lv_obj_t * ui_pnTuringInfo;
lv_obj_t * ui_lbConstLastWater;
lv_obj_t * ui_lbLastWaterInfo;
lv_obj_t * ui_imPlantHum1;
lv_obj_t * ui_lbConstPlantHum1;
lv_obj_t * ui_imPlantHum2;
lv_obj_t * ui_lbConsPlantHum2;
lv_obj_t * ui_lbPlantOneVal;
lv_obj_t * ui_lbPlantTwoVal;
lv_obj_t * ui_imTemp;
lv_obj_t * ui_lbTempVal;
lv_obj_t * ui_barTankVal;
lv_obj_t * ui_lbTankVal;
lv_obj_t * ui_lbTempVal1;
lv_obj_t * ui_pnMainMenu;
lv_obj_t * ui_lbMenuInfo;
lv_obj_t * ui_lbMainMenuInfoUpper;
lv_obj_t * ui_btHomeWifiConfig;
lv_obj_t * ui_Image1;
lv_obj_t * ui_btHomeTuring;
lv_obj_t * ui_imgBtHomeTuring;
lv_obj_t * ui_btHomeWarning;
lv_obj_t * ui_imageBtHomeWarning;
lv_obj_t * ui_btHomeInfo;
lv_obj_t * ui_Image6;
lv_obj_t * ui_btHomeSettings;
lv_obj_t * ui_Image7;
lv_obj_t * ui_btHomeLock;
lv_obj_t * ui_Image8;
lv_obj_t * ui_lbMainMenuInfoLower;
lv_obj_t * ui_btHomeDisableWarning;
lv_obj_t * ui_lbContBtWaterNow4;
lv_obj_t * ui_btHomeWater;
lv_obj_t * ui_Image9;
lv_obj_t * ui_btHomeLight;
lv_obj_t * ui_Image10;
lv_obj_t * ui_btHomeMonitor;
lv_obj_t * ui_imageBtHomeMonitor;
lv_obj_t * ui_pnTest;
lv_obj_t * ui_lbTestLow;
lv_obj_t * ui_lbTestBig;
lv_obj_t * ui_btTest;
lv_obj_t * ui_lbContBtWaterNow2;
lv_obj_t * ui_pnInfo;
lv_obj_t * ui_lbInfoBody;
lv_obj_t * ui_lbInfoTitle;
lv_obj_t * ui_pnSettings;
lv_obj_t * ui_lbSettingsTitle;
lv_obj_t * ui_swEnableLed;
lv_obj_t * ui_lbConstSwLed;
lv_obj_t * ui_lbConstDeep;
lv_obj_t * ui_swDeepSleep;
lv_obj_t * ui_lbConstSS;
lv_obj_t * ui_swEnableSa;
lv_obj_t * ui_lbConstBrightness;
lv_obj_t * ui_slBrightness;
lv_obj_t * ui_btSettingsSetHomeScreen;
lv_obj_t * ui_lbConstBtSettingsReboot1;
lv_obj_t * ui_btSettingsReboot;
lv_obj_t * ui_lbConstBtSettingsReboot;
lv_obj_t * ui_pnSetHomeScreen;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_pnWarnings;
lv_obj_t * ui_lbWarningTitle;
lv_obj_t * ui_pnWarningUpper;
lv_obj_t * ui_lbWarningUpperTitle;
lv_obj_t * ui_lbWarningUpperFooter;
lv_obj_t * ui_pnWarningLower;
lv_obj_t * ui_lbWarningLowerTitle;
lv_obj_t * ui_lbWarningLowerFooter;
lv_obj_t * ui_pnMonitor;
lv_obj_t * ui_lbMonitorBody;
lv_obj_t * ui_lbMonitorTitle;
lv_obj_t * ui_pnNetwork;
lv_obj_t * ui_lbNetworkBody;
lv_obj_t * ui_lbNetworkTitle;
lv_obj_t * ui_btNetworkExtra1;
lv_obj_t * ui_lbNetworkExtra1;
lv_obj_t * ui_btNetworkExtra2;
lv_obj_t * ui_lbNetworkExtra2;
lv_obj_t * ui_btNetworkExtra3;
lv_obj_t * ui_lbNetworkExtra3;
lv_obj_t * ui_ctNavigator;
lv_obj_t * ui_btNavBig;
lv_obj_t * ui_lbBtnNavBig;
lv_obj_t * ui_btNavLeft;
lv_obj_t * ui_imgBtnNavLeft;
lv_obj_t * ui_lbBtnNavLeft;
lv_obj_t * ui_btNavMid;
lv_obj_t * ui_imgBtnNavMid;
lv_obj_t * ui_lbBtnNavMid;
lv_obj_t * ui_btNavRight;
lv_obj_t * ui_imgBtnNavRight;
lv_obj_t * ui_lbBtnNavRight;
lv_obj_t * ui_pnLoading;
lv_obj_t * ui_spinLoadin;
lv_obj_t * ui_lbSpin;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_battery2_[1] = {&ui_img_battery2_48_png};
const lv_img_dsc_t * ui_imgset_battery_[1] = {&ui_img_battery_48_png};
const lv_img_dsc_t * ui_imgset_cog2_[1] = {&ui_img_cog2_48_png};
const lv_img_dsc_t * ui_imgset_cogwheel_[1] = {&ui_img_cogwheel_48_png};
const lv_img_dsc_t * ui_imgset_computer_chip_[1] = {&ui_img_computer_chip_48_png};
const lv_img_dsc_t * ui_imgset_confirm_[2] = {&ui_img_confirm_48_png, &ui_img_confirm_60_png};
const lv_img_dsc_t * ui_imgset_confirm_green_[1] = {&ui_img_confirm_green_48_png};
const lv_img_dsc_t * ui_imgset_cpu_[1] = {&ui_img_cpu_48_png};
const lv_img_dsc_t * ui_imgset_586835308[1] = {&ui_img_673843979};
const lv_img_dsc_t * ui_imgset_gear_[1] = {&ui_img_gear_60_png};
const lv_img_dsc_t * ui_imgset_home_[1] = {&ui_img_home_60_png};
const lv_img_dsc_t * ui_imgset_home_btn_[1] = {&ui_img_home_btn_48_png};
const lv_img_dsc_t * ui_imgset_home_yellow_[1] = {&ui_img_home_yellow_48_png};
const lv_img_dsc_t * ui_imgset_hose__[1] = {&ui_img_hose__60_png};
const lv_img_dsc_t * ui_imgset_hose_[1] = {&ui_img_hose_48_png};
const lv_img_dsc_t * ui_imgset_humidity_[2] = {&ui_img_humidity_48_png, &ui_img_humidity_64_png};
const lv_img_dsc_t * ui_imgset_info_[4] = {&ui_img_info_48_png, &ui_img_info_52_png, &ui_img_info_60_png, &ui_img_info_64_png};
const lv_img_dsc_t * ui_imgset_info_black_[1] = {&ui_img_info_black_48_png};
const lv_img_dsc_t * ui_imgset_info_inv_[1] = {&ui_img_info_inv_48_png};
const lv_img_dsc_t * ui_imgset_light_[2] = {&ui_img_light_48_png, &ui_img_light_60_png};
const lv_img_dsc_t * ui_imgset_lock_[2] = {&ui_img_lock_48_png, &ui_img_lock_60_png};
const lv_img_dsc_t * ui_imgset_1060162954[1] = {&ui_img_1651235431};
const lv_img_dsc_t * ui_imgset_magnifier_[1] = {&ui_img_magnifier_48_png};
const lv_img_dsc_t * ui_imgset_monitor_[1] = {&ui_img_monitor_48_png};
const lv_img_dsc_t * ui_imgset_red_alert_[2] = {&ui_img_red_alert_48_png, &ui_img_red_alert_60_png};
const lv_img_dsc_t * ui_imgset_temperature_[2] = {&ui_img_temperature_48_png, &ui_img_temperature_64_png};
const lv_img_dsc_t * ui_imgset_temperature_leaf_[1] = {&ui_img_temperature_leaf_64_png};
const lv_img_dsc_t * ui_imgset_warning_[2] = {&ui_img_warning_48_png, &ui_img_warning_60_png};
const lv_img_dsc_t * ui_imgset_warning_black_[2] = {&ui_img_warning_black_48_png, &ui_img_warning_black_60_png};
const lv_img_dsc_t * ui_imgset_warning_red_[2] = {&ui_img_warning_red_48_png, &ui_img_warning_red_60_png};
const lv_img_dsc_t * ui_imgset_821147537[2] = {&ui_img_1891597886, &ui_img_1981361452};
const lv_img_dsc_t * ui_imgset_wifi_green_[1] = {&ui_img_wifi_green_60_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
