// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_pnSaveScreen;
extern lv_obj_t * ui_imgLogo;
extern lv_obj_t * ui_lbTimeOnSaveScreen;
extern lv_obj_t * ui_lbSaveScreenInfo;
extern lv_obj_t * ui_SpinSavescreen;
extern lv_obj_t * ui_lbSaveScreenExtra;
extern lv_obj_t * ui_btWiFiPreset1;
extern lv_obj_t * ui_lbWiFiPreset1;
extern lv_obj_t * ui_btWiFiPreset2;
extern lv_obj_t * ui_lbWiFiPreset2;
extern lv_obj_t * ui_rolWifi;
extern lv_obj_t * ui_btWiFiUp;
extern lv_obj_t * ui_lbBtWifiUp;
extern lv_obj_t * ui_btWiFiDown;
extern lv_obj_t * ui_lbBtWifiDown;
extern lv_obj_t * ui_btWiFiScanHome;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_pnTuringInfo;
extern lv_obj_t * ui_lbConstLastWater;
extern lv_obj_t * ui_lbLastWaterInfo;
extern lv_obj_t * ui_imPlantHum1;
extern lv_obj_t * ui_lbConstPlantHum1;
extern lv_obj_t * ui_imPlantHum2;
extern lv_obj_t * ui_lbConsPlantHum2;
extern lv_obj_t * ui_lbPlantOneVal;
extern lv_obj_t * ui_lbPlantTwoVal;
extern lv_obj_t * ui_imTemp;
extern lv_obj_t * ui_lbTempVal;
extern lv_obj_t * ui_barTankVal;
extern lv_obj_t * ui_lbTankVal;
extern lv_obj_t * ui_lbTempVal1;
extern lv_obj_t * ui_pnMainMenu;
extern lv_obj_t * ui_lbMenuInfo;
extern lv_obj_t * ui_lbMainMenuInfoUpper;
extern lv_obj_t * ui_btHomeWifiConfig;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_btHomeTuring;
extern lv_obj_t * ui_imgBtHomeTuring;
extern lv_obj_t * ui_btHomeWarning;
extern lv_obj_t * ui_imageBtHomeWarning;
extern lv_obj_t * ui_btHomeInfo;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_btHomeSettings;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_btHomeLock;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_lbMainMenuInfoLower;
extern lv_obj_t * ui_btHomeDisableWarning;
extern lv_obj_t * ui_lbContBtWaterNow4;
extern lv_obj_t * ui_btHomeWater;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_btHomeLight;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_btHomeMonitor;
extern lv_obj_t * ui_imageBtHomeMonitor;
extern lv_obj_t * ui_pnTest;
extern lv_obj_t * ui_lbTestLow;
extern lv_obj_t * ui_lbTestBig;
extern lv_obj_t * ui_btTest;
extern lv_obj_t * ui_lbContBtWaterNow2;
extern lv_obj_t * ui_pnInfo;
extern lv_obj_t * ui_lbInfoBody;
extern lv_obj_t * ui_lbInfoTitle;
extern lv_obj_t * ui_pnSettings;
extern lv_obj_t * ui_lbSettingsTitle;
extern lv_obj_t * ui_swEnableLed;
extern lv_obj_t * ui_lbConstSwLed;
extern lv_obj_t * ui_lbConstDeep;
extern lv_obj_t * ui_swDeepSleep;
extern lv_obj_t * ui_lbConstSS;
extern lv_obj_t * ui_swEnableSa;
extern lv_obj_t * ui_lbConstBrightness;
extern lv_obj_t * ui_slBrightness;
extern lv_obj_t * ui_btSettingsSetHomeScreen;
extern lv_obj_t * ui_lbConstBtSettingsReboot1;
extern lv_obj_t * ui_btSettingsReboot;
extern lv_obj_t * ui_lbConstBtSettingsReboot;
extern lv_obj_t * ui_pnSetHomeScreen;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_pnWarnings;
extern lv_obj_t * ui_lbWarningTitle;
extern lv_obj_t * ui_pnWarningUpper;
extern lv_obj_t * ui_lbWarningUpperTitle;
extern lv_obj_t * ui_lbWarningUpperFooter;
extern lv_obj_t * ui_pnWarningLower;
extern lv_obj_t * ui_lbWarningLowerTitle;
extern lv_obj_t * ui_lbWarningLowerFooter;
extern lv_obj_t * ui_pnMonitor;
extern lv_obj_t * ui_lbMonitorBody;
extern lv_obj_t * ui_lbMonitorTitle;
extern lv_obj_t * ui_pnNetwork;
extern lv_obj_t * ui_lbNetworkBody;
extern lv_obj_t * ui_lbNetworkTitle;
extern lv_obj_t * ui_btNetworkExtra1;
extern lv_obj_t * ui_lbNetworkExtra1;
extern lv_obj_t * ui_btNetworkExtra2;
extern lv_obj_t * ui_lbNetworkExtra2;
extern lv_obj_t * ui_btNetworkExtra3;
extern lv_obj_t * ui_lbNetworkExtra3;
extern lv_obj_t * ui_ctNavigator;
extern lv_obj_t * ui_btNavBig;
extern lv_obj_t * ui_lbBtnNavBig;
extern lv_obj_t * ui_btNavLeft;
extern lv_obj_t * ui_imgBtnNavLeft;
extern lv_obj_t * ui_lbBtnNavLeft;
extern lv_obj_t * ui_btNavMid;
extern lv_obj_t * ui_imgBtnNavMid;
extern lv_obj_t * ui_lbBtnNavMid;
extern lv_obj_t * ui_btNavRight;
extern lv_obj_t * ui_imgBtnNavRight;
extern lv_obj_t * ui_lbBtnNavRight;
extern lv_obj_t * ui_pnLoading;
extern lv_obj_t * ui_spinLoadin;
extern lv_obj_t * ui_lbSpin;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1651235431);    // assets/logo-no-background240.png
LV_IMG_DECLARE(ui_img_home_60_png);    // assets/home_60.png
LV_IMG_DECLARE(ui_img_humidity_48_png);    // assets/humidity_48.png
LV_IMG_DECLARE(ui_img_temperature_leaf_64_png);    // assets/temperature_leaf_64.png
LV_IMG_DECLARE(ui_img_wifi_green_60_png);    // assets/wifi_green_60.png
LV_IMG_DECLARE(ui_img_temperature_48_png);    // assets/temperature_48.png
LV_IMG_DECLARE(ui_img_warning_red_48_png);    // assets/warning_red_48.png
LV_IMG_DECLARE(ui_img_info_60_png);    // assets/info_60.png
LV_IMG_DECLARE(ui_img_gear_60_png);    // assets/gear_60.png
LV_IMG_DECLARE(ui_img_lock_60_png);    // assets/lock_60.png
LV_IMG_DECLARE(ui_img_hose__60_png);    // assets/hose _60.png
LV_IMG_DECLARE(ui_img_light_60_png);    // assets/light_60.png
LV_IMG_DECLARE(ui_img_monitor_48_png);    // assets/monitor_48.png
LV_IMG_DECLARE(ui_img_confirm_48_png);    // assets/confirm_48.png
LV_IMG_DECLARE(ui_img_magnifier_48_png);    // assets/magnifier_48.png
LV_IMG_DECLARE(ui_img_home_yellow_48_png);    // assets/home_yellow_48.png
LV_IMG_DECLARE(ui_img_battery2_48_png);    // assets/battery2_48.png
LV_IMG_DECLARE(ui_img_battery_48_png);    // assets/battery_48.png
LV_IMG_DECLARE(ui_img_cog2_48_png);    // assets/cog2_48.png
LV_IMG_DECLARE(ui_img_cogwheel_48_png);    // assets/cogwheel_48.png
LV_IMG_DECLARE(ui_img_computer_chip_48_png);    // assets/computer_chip_48.png
LV_IMG_DECLARE(ui_img_confirm_60_png);    // assets/confirm_60.png
LV_IMG_DECLARE(ui_img_confirm_green_48_png);    // assets/confirm_green_48.png
LV_IMG_DECLARE(ui_img_cpu_48_png);    // assets/cpu_48.png
LV_IMG_DECLARE(ui_img_673843979);    // assets/database-storage_48.png
LV_IMG_DECLARE(ui_img_home_btn_48_png);    // assets/home_btn_48.png
LV_IMG_DECLARE(ui_img_hose_48_png);    // assets/hose_48.png
LV_IMG_DECLARE(ui_img_humidity_64_png);    // assets/humidity_64.png
LV_IMG_DECLARE(ui_img_info_48_png);    // assets/info_48.png
LV_IMG_DECLARE(ui_img_info_52_png);    // assets/info_52.png
LV_IMG_DECLARE(ui_img_info_64_png);    // assets/info_64.png
LV_IMG_DECLARE(ui_img_info_black_48_png);    // assets/info_black_48.png
LV_IMG_DECLARE(ui_img_info_inv_48_png);    // assets/info_inv_48.png
LV_IMG_DECLARE(ui_img_light_48_png);    // assets/light_48.png
LV_IMG_DECLARE(ui_img_lock_48_png);    // assets/lock_48.png
LV_IMG_DECLARE(ui_img_red_alert_48_png);    // assets/red_alert_48.png
LV_IMG_DECLARE(ui_img_red_alert_60_png);    // assets/red_alert_60.png
LV_IMG_DECLARE(ui_img_temperature_64_png);    // assets/temperature_64.png
LV_IMG_DECLARE(ui_img_warning_48_png);    // assets/warning_48.png
LV_IMG_DECLARE(ui_img_warning_60_png);    // assets/warning_60.png
LV_IMG_DECLARE(ui_img_warning_black_48_png);    // assets/warning_black_48.png
LV_IMG_DECLARE(ui_img_warning_black_60_png);    // assets/warning_black_60.png
LV_IMG_DECLARE(ui_img_warning_red_60_png);    // assets/warning_red_60.png
LV_IMG_DECLARE(ui_img_1891597886);    // assets/water-tank_48.png
LV_IMG_DECLARE(ui_img_1981361452);    // assets/water-tank_64.png



LV_FONT_DECLARE(ui_font_ibmmono);
LV_FONT_DECLARE(ui_font_Pappermint);
LV_FONT_DECLARE(ui_font_Rubik_Mono);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
